fix(xAxis): minor ticks depending on interval #43377043
TechAudit-BI/echarts pull request #10
Opened 2024-12-23 15:15 UTC by aspectie

Карточки в Kaiten:
https://techaudit.kaiten.ru/43377043

Причина бага: количество минорных делений берется дефолтное 5, что никак не соотносится с величиной промежутка между двумя значениями.

Решение: в зависимости от длины промежутка вычислять количество делений в разных масштабах (часы, дни, месяцы и тд)

2024-12-28 09:04 UTC, lmmelstron commented on src/scale/Time.ts
> +    getTicks(expandToNicedExtent?: boolean, onlyMaxLevel?: boolean): TimeScaleTick[] {
Я не вижу в коде использования `expandToNicedExtent`

2024-12-28 09:26 UTC, lmmelstron commented on src/scale/Interval.ts
> +    getTicks(expandToNicedExtent?: boolean, onlyMaxLevel?: boolean): ScaleTick[] {
Нужно либо дописать комментарий, чтобы было явно понятно, зачем это сделано, либо заменять уже на объект. Без контекста это выглядит опечаткой. Использование множественных опциональных, не используемых параметров потом замучаемся дебажить. Не так давно сталкивался.

Особенно, учитывая то, что мы периодически мёрджим обновления апача с оверрайдом наших изменений и последующим ручным восстановлением.

2024-12-28 10:02 UTC, lmmelstron commented on src/scale/Interval.ts
> +        const unitMap: Partial<Record<TimeUnit, () => number>> = {
мне не очень понятно, зачем так много копипаста функций, почему не сделать так..

```ts
const getSplit = (period:number) => (val: number) => Math.ceil(val / period)
const unitMap: Partial<Record<TimeUnit, (val: number) => number>> = {
    'second': getSplit(ONE_SECOND),
    ...
}
```

2024-12-28 10:20 UTC, lmmelstron commented on src/scale/Interval.ts
> +    getMinorTicks(): number[][] {
В чём причина того, что ты модифицируешь родительский класс, а не класс времени?

2024-12-28 11:04 UTC, lmmelstron requested changes
interval, судя по коду, не обязан быть временным, поэтому прописывать в нём логику вложенных тиков на основе времени кажется неправильным. 
Необходимо проверить, и, если это действительно так, перенести логику в Time. 

Так же есть пара комментариев по оптимизации кода

2025-01-13 14:26 UTC, rekilina requested changes

2025-01-13 14:26 UTC, rekilina commented on src/util/time.ts
> +export const ONE_LEAP_YEAR = ONE_DAY * 366;
Зачем нужно вводить високосный год? при расчете числа делений все равно используется ceil, и кажется, что разницы нет

2025-01-13 14:26 UTC, rekilina commented on src/scale/Time.ts
> +        const unitMap: Partial<Record<TimeUnit, number>> = {
`Object.fromEntries(scaleIntervals)`

2025-01-13 14:26 UTC, rekilina commented on src/scale/Time.ts
> +        const unitMap: Partial<Record<TimeUnit, number>> = {
правда тогда придется поменять compiler target на es2019

2025-01-13 14:26 UTC, rekilina commented on src/scale/Time.ts
> +            ticks = getLevelTicks(levelTicks, i);
Если так делать, то потеряются первые числа месяца / года
Нужно ticks объединять через concat например, или как-то переписать это место

2025-01-13 14:26 UTC, rekilina commented on src/scale/Time.ts
> + else {
отступ

2025-01-14 09:21 UTC, aspectie commented on src/util/time.ts
> +export const ONE_LEAP_YEAR = ONE_DAY * 366;
между високосным и невисокосным годами интервал больше, поэтому Math.ceil(interval / period) будет > 1, то есть между ними появляется лишний minor tick

2025-01-31 08:34 UTC, lmmelstron approved these changes
Вроде норм. Мне не очень нравится копипаст значений дат. Но я вижу, что момент "разрешён".

2025-02-14 13:38 UTC, merged