WIP: feat(xAxis): change xAxis tick interval counting
TechAudit-BI/echarts pull request #9
Opened 2024-10-17 08:37 UTC by shulepovalidiya

2024-10-23 07:15 UTC, lmmelstron commented on src/scale/Time.ts
> +                        : getDateInterval(approxInterval, 31); // Use 32 days and let interval been 16
Этот тетрарный оператор повторяется 6 раз в этом файле/ я бы вынес его в отдельную функцию перед switch, и сделать что-то типа
`case 'day': interval = getCustomInterval(ONE_DAY) ?? getDateInterval(approxInterval, 31);`

2024-10-23 07:17 UTC, lmmelstron commented on src/scale/Time.ts
> +                        ? customInterval / (30 * ONE_DAY)
А в месяце точно 30 дней? Я проверю, но при работе с месяцами мне часто приходилось брать точные значения

2024-10-23 07:18 UTC, lmmelstron commented on src/scale/Time.ts
> +        notAdd?: boolean;
Если его убрали, то есть ли смысл его оставлять?

2024-10-23 07:40 UTC, lmmelstron commented on src/scale/Time.ts
> +    isIntervalCustom: boolean,
По тому, что я вижу, `isIntervalCustom` тебе нужен исключительно для того, чтобы игнорировать `customInterval` внутри функции. Может быть просто тогда просто сделать 
`customInterval: number | undefined,`
и
```
const innerTicks = getIntervalTicks(
          ...
          this._isIntervalCustom ? interval : undefined,
          ...
```

2024-10-23 07:46 UTC, lmmelstron requested changes
Посмотрел, большинство комментариев просто оптимизация. Единственное, за что зацепился взгляд, это жёсткий выбор 30 дней для месяца. Я не уверен, что это правильно?

2024-10-23 07:55 UTC, lmmelstron commented on src/scale/Time.ts
> +                .map(tick => tick.value);
filter + map = reduce

2024-10-23 07:58 UTC, lmmelstron commented on src/scale/Time.ts
> +            const newStartTick = noAddedTicks.slice(-1)?.[0];
раз уж добавила новую переменную, то можно и fallback на `startTick `сделать здесь

2024-10-30 07:15 UTC, shulepovalidiya commented on src/scale/Time.ts
> +                        ? customInterval / (30 * ONE_DAY)
Опиралась на расчёты echarts (функция getMonthInterval). Но если это нужно исправить, внесу исправления

2024-10-30 07:59 UTC, shulepovalidiya commented on src/scale/Time.ts
> +                .map(tick => tick.value);
На мой взгляд вариант с filter и map более читаемый, чем с reduce + массив тиков обычно небольшой (то есть,  разница в производительности не очень значительная). Но если такой вариант будет здесь более подходящим, я перепишу

2024-10-30 08:02 UTC, lmmelstron commented on src/scale/Time.ts
> +                .map(tick => tick.value);
конкретно здесь чисто вкусовщина)) 
Более интересный момент, что filter+map+slice можно заменить на newAddedTicks.findLast

2024-10-30 08:27 UTC, shulepovalidiya commented on src/scale/Time.ts
> +                .map(tick => tick.value);
На мой взгляд, вариант с filter и map выглядит более читаемым + массив тиков обычно небольшой, поэтому выигрыш в производительности тоже кажется не очень значительным. Но вариант с reduce более подходящий здесь, то перепишу на reduce

2024-10-30 08:27 UTC, shulepovalidiya commented on src/scale/Time.ts
> +            const newStartTick = noAddedTicks.slice(-1)?.[0];
Кажется, метод `findLast` использовать не получится из-за конфига TypeScript ("target": "ES3").

2024-10-30 08:30 UTC, lmmelstron commented on src/scale/Time.ts
> +            const newStartTick = noAddedTicks.slice(-1)?.[0];
эх, он бы сюда хорошо подошёл. Да, август 22 года, совсем свежий метод..

2024-10-30 08:45 UTC, shulepovalidiya commented on src/scale/Time.ts
> +            const newStartTick = noAddedTicks.slice(-1)?.[0];
Кажется, для использования метода `findLast` нужно изменить tsconfig, так как сейчас TS этот метод не распознаёт - `TS2339: Property findLast does not exist on type number[]`.

2024-10-30 09:20 UTC, shulepovalidiya commented on src/scale/Time.ts
> +                        : getDateInterval(approxInterval, 31); // Use 32 days and let interval been 16
Спасибо! Вынесла в функцию `getCustomInterval`

2024-10-30 09:20 UTC, shulepovalidiya commented on src/scale/Time.ts
> +        notAdd?: boolean;
Спасибо! Закомментировала это поле и в типизации

2024-10-30 09:21 UTC, shulepovalidiya commented on src/scale/Time.ts
> +    isIntervalCustom: boolean,
Спасибо! Сделала

2024-10-30 09:32 UTC, lmmelstron approved these changes
выглядит норм

2024-11-02 09:41 UTC, merged